version: '3.1'
services:
    database:
        image: mysql:5.7
        working_dir: /app
        volumes:
            - './app:/app'
        env_file: './docker/db/config/.env'
        ports:
            - '3306:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - './app:/app'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '23000:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /app
        volumes:
            - './app:/app'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - database
        env_file: './docker/db/config/.env'
        ports:
            - '23002:80'